# Use an official Ubuntu base image
FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc

# Set the working directory
WORKDIR /app

# Copy the client.c source file to the container
COPY client.c .

# Compile the client program
RUN gcc client.c -o client

# Set the entry point to run the client program
ENTRYPOINT ["./client"]
CMD ["server.default.svc.cluster.local"]
