apiVersion: v1
kind: Pod
metadata:
  name: server
  namespace: default
  labels:
    run: server
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/notify.json
  restartPolicy: Never
  containers:
  - name: server
    image: haih/server
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: default
spec:
  selector:
    run: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
